version: "3.7"
services:
  frontend:
    image: dappros/web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./init.sh:/init.sh
    environment:
      - API_URL=https://xxx.domain.con/v1
      - APP_DOMAIN=domain.com
    command:
      [
        "sh",
        "/init.sh"
      ]