name: Build and Push Docker image for client-web to DockerHub
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'client-web/**'
on:
  push:
    tags:
      - 'web-client-*.*.*'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: client-web
          file: client-web/dockerfolder/Dockerfile
          push: true
          tags: dappros/web:${{ env.RELEASE_VERSION }}
